In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("../data/train.csv")

In [4]:
df.describecribe()

,data_id,c1,c2,c3,c4,c5,c6,c7,c8,c9,...,c80,c81,c82,c83,c84,c85,c86,c87,c88,target
count,5.600000e+05,560000.000000,560000.000000,560000.000000,560000.000000,560000.000000,560000.000000,560000.000000,560000.000000,560000.000000,...,560000.000000,560000.000000,560000.000000,560000.000000,560000.000000,560000.000000,560000.000000,560000.000000,560000.000000,560000.0
mean,7.329990e+05,0.007557,-0.000052,-0.000503,-0.001149,0.000169,0.003947,0.007683,0.008374,-0.000930,...,-0.017249,-0.000613,0.010724,-0.000928,0.009099,0.003673,0.006469,0.000440,-0.016546,0.5
std,4.232408e+05,1.028555,0.022317,0.020689,0.065025,0.013475,0.052914,0.044448,0.195341,0.026407,...,0.128480,0.043250,0.057170,0.126877,0.037613,0.035605,0.051869,0.048754,1.025204,0.5
min,2.000000e+00,-4.014821,-0.697343,-0.477931,-1.737655,-0.221279,-0.410262,-0.294782,0.000000,-0.495582,...,-0.999063,-1.270283,-0.033371,-2.706026,-0.047106,-0.085568,-0.086284,-1.785200,-4.159360,0.0
25%,3.664285e+05,-0.786552,-0.007315,-0.007192,-0.020416,-0.000000,0.000000,0.000000,0.000000,-0.009333,...,-0.061520,-0.010795,0.000000,-0.036212,0.000000,0.000000,0.000000,-0.013494,-0.811286,0.0
50%,7.330480e+05,0.002374,0.000002,-0.000077,-0.000150,-0.000000,0.000000,0.000000,0.000000,-0.000184,...,-0.002801,-0.000016,0.000000,-0.000489,0.000000,0.000000,0.000000,0.000031,-0.025170,0.5
75%,1.099738e+06,0.800852,0.007044,0.006404,0.018240,0.000000,0.000000,0.000000,0.000000,0.007996,...,0.044754,0.010828,0.000000,0.032696,0.000000,0.000000,0.000000,0.014327,0.775868,1.0
max,1.466094e+06,4.274689,0.460489,0.540909,1.378423,0.418434,1.355478,0.793288,6.600661,0.322109,...,0.845139,0.617547,0.659691,2.664469,0.435074,0.704358,0.965180,1.186017,3.961918,1.0

In [13]:
df[df['period'] == 'train1'].describe()

,data_id,c1,c2,c3,c4,c5,c6,c7,c8,c9,...,c80,c81,c82,c83,c84,c85,c86,c87,c88,target
count,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,...,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000
mean,52176.519400,-0.085909,-0.000404,0.000231,-0.000188,0.000669,0.002954,0.006067,0.009211,0.000462,...,-0.006264,-0.001206,0.009506,-0.002389,0.007142,0.002963,0.005733,0.000547,0.152055,0.500000
std,30213.331814,1.020249,0.024852,0.008546,0.020957,0.008057,0.043040,0.035269,0.205835,0.012172,...,0.041815,0.011937,0.051075,0.044597,0.027001,0.027227,0.046567,0.059724,0.988894,0.500006
min,2.000000,-3.086219,-0.697343,-0.060078,-0.101143,-0.058013,-0.281778,-0.086645,0.000000,-0.111715,...,-0.301357,-0.167550,-0.033371,-0.290237,0.000000,-0.004597,-0.008605,-1.785200,-3.402684,0.000000
25%,25980.750000,-0.874606,-0.005652,-0.003069,-0.006839,0.000000,0.000000,0.000000,0.000000,-0.003732,...,-0.025523,-0.004609,0.000000,-0.017261,0.000000,0.000000,0.000000,-0.018546,-0.602591,0.000000
50%,52093.500000,-0.156231,0.000248,0.000061,0.000021,0.000000,0.000000,0.000000,0.000000,0.000218,...,-0.003414,-0.000282,0.000000,-0.000779,0.000000,0.000000,0.000000,0.000008,0.178903,0.500000
75%,78399.250000,0.688178,0.007499,0.003414,0.005878,0.000000,0.000000,0.000000,0.000000,0.004981,...,0.016410,0.002815,0.000000,0.011816,0.000000,0.000000,0.000000,0.019736,0.883131,1.000000
max,104721.000000,3.593416,0.119091,0.088138,0.519066,0.159202,0.783428,0.354438,4.839669,0.086925,...,0.311416,0.164881,0.429171,0.615827,0.211848,0.414371,0.696936,0.975594,3.609878,1.000000

In [14]:
df[df['period'] == 'train2'].describe()

,data_id,c1,c2,c3,c4,c5,c6,c7,c8,c9,...,c80,c81,c82,c83,c84,c85,c86,c87,c88,target
count,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,...,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000
mean,156919.662250,-0.245849,-0.002506,0.000095,0.001415,0.001650,0.004446,0.006894,0.005137,-0.003811,...,-0.032837,0.001411,0.009610,0.001484,0.009992,0.003311,0.005661,-0.000438,0.025357,0.500000
std,30167.979799,1.002424,0.025377,0.013806,0.032831,0.018993,0.062138,0.042553,0.115518,0.025864,...,0.149275,0.086629,0.050915,0.054561,0.040192,0.032808,0.044100,0.028375,0.942867,0.500006
min,104722.000000,-3.773082,-0.129001,-0.092801,-0.217431,-0.128732,-0.231406,-0.121134,0.000000,-0.170553,...,-0.999063,-1.270283,0.000000,-0.511617,-0.025136,-0.012706,0.000000,-0.385764,-3.239170,0.000000
25%,130819.750000,-0.993031,-0.014310,-0.004487,-0.010896,0.000000,0.000000,0.000000,0.000000,-0.018116,...,-0.099053,-0.027441,0.000000,-0.017300,0.000000,0.000000,0.000000,-0.010902,-0.689508,0.000000
50%,156894.500000,-0.285462,-0.001616,0.000039,0.000347,0.000000,0.000000,0.000000,0.000000,-0.002637,...,-0.011547,0.003369,0.000000,0.000109,0.000000,0.000000,0.000000,-0.000396,0.016850,0.500000
75%,183077.250000,0.490081,0.007347,0.004811,0.013337,0.000000,0.000000,0.000000,0.000000,0.009117,...,0.057611,0.038786,0.000000,0.019685,0.000000,0.000000,0.000000,0.008976,0.743366,1.000000
max,209441.000000,3.027385,0.150808,0.112138,0.331615,0.340251,1.335058,0.561098,3.817592,0.192150,...,0.542219,0.384821,0.436748,0.739793,0.383729,0.655821,0.766828,0.266268,3.417540,1.000000

In [15]:
df[df['period'] == 'train3'].describe()

,data_id,c1,c2,c3,c4,c5,c6,c7,c8,c9,...,c80,c81,c82,c83,c84,c85,c86,c87,c88,target
count,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,...,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000
mean,261940.313975,0.026343,-0.002135,0.000325,-0.000277,-0.001026,0.003731,0.010498,0.008347,-0.000014,...,-0.030747,0.001144,0.011292,-0.007291,0.016323,0.006585,0.008101,0.000478,-0.104684,0.500000
std,30247.937210,0.938188,0.023726,0.016528,0.071244,0.010575,0.050278,0.062299,0.186473,0.009484,...,0.182007,0.074808,0.057690,0.078891,0.062611,0.058803,0.060540,0.015048,0.848865,0.500006
min,209444.000000,-2.580048,-0.143347,-0.177628,-0.690181,-0.152478,-0.146850,-0.080990,0.000000,-0.055905,...,-0.759755,-0.686133,-0.000000,-0.532144,-0.047106,0.000000,0.000000,-0.137249,-2.883940,0.000000
25%,235664.500000,-0.742274,-0.015353,-0.007203,-0.038575,0.000000,0.000000,0.000000,0.000000,-0.003055,...,-0.122570,-0.037076,0.000000,-0.042983,0.000000,0.000000,0.000000,-0.005160,-0.756177,0.000000
50%,262061.500000,0.002453,-0.002154,-0.000159,-0.001133,-0.000000,0.000000,0.000000,0.000000,-0.000008,...,-0.017663,0.002743,0.000000,-0.003828,0.000000,0.000000,0.000000,-0.000042,-0.127805,0.500000
75%,288326.750000,0.782358,0.008994,0.006916,0.036987,0.000000,0.000000,0.000000,0.000000,0.002973,...,0.090654,0.043141,0.000000,0.030036,0.000000,0.000000,0.000000,0.005287,0.521009,1.000000
max,314159.000000,2.698820,0.190272,0.114695,0.463223,0.081698,0.960596,0.647532,4.228473,0.075779,...,0.480963,0.305703,0.397762,0.332683,0.419971,0.704358,0.793317,0.112457,3.004963,1.000000

In [16]:
df[df['period'] == 'train4'].describe()

,data_id,c1,c2,c3,c4,c5,c6,c7,c8,c9,...,c80,c81,c82,c83,c84,c85,c86,c87,c88,target
count,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,...,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000
mean,366448.274650,0.194275,0.000022,0.001134,0.001854,-0.001019,0.002794,0.008038,0.011673,-0.002790,...,-0.030073,-0.007718,0.015024,-0.017868,0.007066,0.002204,0.005660,0.004563,0.147026,0.500000
std,30220.480654,0.993199,0.011474,0.016211,0.049617,0.011711,0.039132,0.045787,0.260805,0.017819,...,0.134681,0.056498,0.079172,0.155237,0.027452,0.021621,0.045526,0.060560,1.117843,0.500006
min,314167.000000,-3.170218,-0.101758,-0.096984,-0.342562,-0.181821,-0.200422,-0.148241,0.000000,-0.212850,...,-0.901700,-1.166294,0.000000,-2.490106,0.000000,-0.058704,-0.038824,-0.281494,-3.386312,0.000000
25%,340317.750000,-0.547481,-0.003520,-0.005499,-0.019518,-0.000000,0.000000,0.000000,0.000000,-0.009165,...,-0.091984,-0.028187,0.000000,-0.083189,0.000000,0.000000,0.000000,-0.022609,-0.788257,0.000000
50%,366428.000000,0.266653,0.000021,0.000312,0.000530,0.000000,0.000000,0.000000,0.000000,-0.000997,...,-0.015051,-0.001859,0.000000,-0.006136,0.000000,0.000000,0.000000,0.000644,0.167452,0.500000
75%,392577.250000,0.986977,0.003843,0.006674,0.022055,-0.000000,0.000000,0.000000,0.000000,0.004756,...,0.039505,0.019189,0.000000,0.054801,0.000000,0.000000,0.000000,0.030004,1.063834,1.000000
max,418884.000000,2.813221,0.079254,0.301534,1.025511,0.090341,0.691060,0.516143,6.079524,0.134326,...,0.535900,0.319507,0.659691,0.732524,0.222631,0.306702,0.624619,1.186017,3.176456,1.000000

In [17]:
df[df['period'] == 'train5'].describe()

,data_id,c1,c2,c3,c4,c5,c6,c7,c8,c9,...,c80,c81,c82,c83,c84,c85,c86,c87,c88,target
count,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,...,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000
mean,471321.255625,-0.036371,0.000451,-0.001156,-0.001684,-0.000944,0.002350,0.009228,0.007704,0.000562,...,-0.012578,-0.000177,0.010583,-0.002826,0.010806,0.005458,0.006566,0.003719,0.103733,0.500000
std,30223.557070,1.008683,0.013641,0.015247,0.053893,0.012317,0.035766,0.054775,0.174689,0.009051,...,0.152832,0.043265,0.054369,0.069508,0.043347,0.048917,0.048860,0.045641,1.067645,0.500006
min,418885.000000,-3.502274,-0.108408,-0.216335,-0.321477,-0.208119,-0.293611,-0.140377,0.000000,-0.057714,...,-0.769375,-0.437970,0.000000,-0.957752,-0.016798,0.000000,0.000000,-0.255630,-3.527771,0.000000
25%,445080.500000,-0.777306,-0.003597,-0.005473,-0.025447,-0.000000,0.000000,0.000000,0.000000,-0.002788,...,-0.089967,-0.018619,0.000000,-0.022167,0.000000,0.000000,0.000000,-0.012704,-0.699410,0.000000
50%,471416.000000,-0.070939,0.000343,-0.000089,-0.001290,-0.000000,0.000000,0.000000,0.000000,0.000090,...,0.002599,0.000213,0.000000,-0.000009,0.000000,0.000000,0.000000,0.000319,0.160030,0.500000
75%,497564.500000,0.707592,0.005159,0.004876,0.020678,0.000000,0.000000,0.000000,0.000000,0.003374,...,0.076551,0.019958,0.000000,0.020717,0.000000,0.000000,0.000000,0.016850,0.936628,1.000000
max,523605.000000,3.598843,0.157852,0.070802,0.515309,0.083754,0.692688,0.793288,4.795112,0.082247,...,0.748277,0.290399,0.476785,0.465463,0.423725,0.630323,0.742539,0.544363,3.490501,1.000000

In [18]:
df[df['period'] == 'train6'].describe()

,data_id,c1,c2,c3,c4,c5,c6,c7,c8,c9,...,c80,c81,c82,c83,c84,c85,c86,c87,c88,target
count,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,...,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000
mean,575947.906475,0.060154,0.000235,-0.002081,-0.001054,0.001182,0.005241,0.007940,0.010275,-0.000974,...,-0.000546,-0.000795,0.013601,0.006250,0.016560,0.004944,0.007499,-0.002409,-0.232432,0.500000
std,30220.817950,1.042771,0.010006,0.035437,0.070009,0.010476,0.062184,0.041997,0.229678,0.046004,...,0.035359,0.027416,0.069447,0.206007,0.062218,0.046174,0.055241,0.096807,1.061398,0.500006
min,523607.000000,-3.428683,-0.063882,-0.477931,-0.745843,-0.007518,-0.023065,0.000000,0.000000,-0.400838,...,-0.169858,-0.401110,0.000000,-1.289148,0.000000,-0.000895,0.000000,-1.193551,-3.668760,0.000000
25%,549779.500000,-0.740713,-0.003256,-0.013898,-0.033874,0.000000,0.000000,0.000000,0.000000,-0.022633,...,-0.019102,-0.008026,0.000000,-0.091546,0.000000,0.000000,0.000000,-0.045409,-1.097478,0.000000
50%,575887.000000,0.054332,-0.000033,-0.000063,-0.000355,0.000000,0.000000,0.000000,0.000000,0.001053,...,-0.001172,0.000320,0.000000,-0.002834,0.000000,0.000000,0.000000,0.001554,-0.305741,0.500000
75%,602046.750000,0.857253,0.003139,0.013741,0.032606,0.000000,0.000000,0.000000,0.000000,0.025081,...,0.017212,0.009573,0.000000,0.078757,0.000000,0.000000,0.000000,0.050321,0.612016,1.000000
max,628326.000000,3.916848,0.115785,0.392145,0.768288,0.179349,1.090166,0.403862,5.422224,0.218656,...,0.287351,0.233128,0.513248,2.664469,0.435074,0.650242,0.649293,0.339973,3.098402,1.000000

In [19]:
df[df['period'] == 'train7'].describe()

,data_id,c1,c2,c3,c4,c5,c6,c7,c8,c9,...,c80,c81,c82,c83,c84,c85,c86,c87,c88,target
count,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,...,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000
mean,680398.880350,0.166444,0.000262,-0.002505,0.000340,0.000798,0.003740,0.006875,0.010012,-0.001841,...,-0.003515,0.000007,0.010402,0.009650,0.010874,0.003510,0.006412,-0.003967,-0.165498,0.500000
std,30227.960643,1.008281,0.009266,0.027848,0.041408,0.008361,0.048696,0.037032,0.224882,0.039946,...,0.042980,0.015345,0.054607,0.150346,0.042418,0.032145,0.049072,0.070406,1.002355,0.500006
min,628331.000000,-3.762124,-0.054443,-0.464228,-0.248383,-0.028524,-0.214407,-0.002425,0.000000,-0.437371,...,-0.248269,-0.100034,0.000000,-0.630413,0.000000,0.000000,0.000000,-0.952715,-3.439569,0.000000
25%,654157.750000,-0.559075,-0.003320,-0.008332,-0.010046,0.000000,0.000000,0.000000,0.000000,-0.020640,...,-0.022780,-0.005116,0.000000,-0.035457,0.000000,0.000000,0.000000,-0.026008,-0.939501,0.000000
50%,680288.500000,0.188522,0.000053,-0.000229,0.000168,0.000000,0.000000,0.000000,0.000000,0.000526,...,-0.002127,0.000157,0.000000,0.000255,0.000000,0.000000,0.000000,0.000086,-0.210010,0.500000
75%,706581.250000,0.931367,0.003639,0.006727,0.009821,0.000000,0.000000,0.000000,0.000000,0.021210,...,0.018348,0.005575,0.000000,0.041148,0.000000,0.000000,0.000000,0.023149,0.570236,1.000000
max,733046.000000,3.561816,0.148134,0.136672,0.940086,0.162219,0.938518,0.385264,5.553981,0.190721,...,0.688998,0.313573,0.463678,2.556480,0.318660,0.438374,0.646329,0.306117,3.318053,1.000000

In [20]:
df[df['period'] == 'train8'].describe()

,data_id,c1,c2,c3,c4,c5,c6,c7,c8,c9,...,c80,c81,c82,c83,c84,c85,c86,c87,c88,target
count,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,...,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000
mean,785242.902025,-0.148558,0.001046,0.000176,-0.007839,0.001307,0.005414,0.009293,0.005609,-0.001330,...,-0.008876,-0.000998,0.010246,0.007747,0.007422,0.004330,0.008009,0.000542,0.151408,0.500000
std,30200.228846,1.040701,0.019782,0.009549,0.138082,0.014298,0.062480,0.049886,0.125320,0.025821,...,0.137978,0.018585,0.052940,0.222473,0.027610,0.039400,0.060728,0.017019,0.959444,0.500006
min,733050.000000,-3.315841,-0.097515,-0.074209,-0.862763,-0.020683,0.000000,0.000000,0.000000,-0.112163,...,-0.650409,-0.119424,0.000000,-2.706026,0.000000,0.000000,0.000000,-0.077731,-3.009940,0.000000
25%,759018.750000,-0.979187,-0.006966,-0.003009,-0.087932,0.000000,0.000000,0.000000,0.000000,-0.012170,...,-0.075221,-0.006071,0.000000,-0.089855,0.000000,0.000000,0.000000,-0.005927,-0.642548,0.000000
50%,785052.500000,-0.199834,0.000071,0.000046,-0.007964,0.000000,0.000000,0.000000,0.000000,-0.000675,...,0.012744,-0.000049,0.000000,0.006656,0.000000,0.000000,0.000000,-0.000098,0.255414,0.500000
75%,811527.250000,0.661270,0.008469,0.003751,0.066660,0.000000,0.000000,0.000000,0.000000,0.009316,...,0.077887,0.004735,0.000000,0.115974,0.000000,0.000000,0.000000,0.005983,0.942776,1.000000
max,837767.000000,3.116269,0.151453,0.071039,1.378423,0.261078,1.218285,0.432481,2.902383,0.178954,...,0.469060,0.155986,0.408945,1.502280,0.174031,0.534966,0.742541,0.262663,2.731756,1.000000

In [21]:
df[df['period'] == 'train9'].describe()

,data_id,c1,c2,c3,c4,c5,c6,c7,c8,c9,...,c80,c81,c82,c83,c84,c85,c86,c87,c88,target
count,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,...,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000
mean,890156.069250,-0.048139,-0.000021,-0.001955,-0.001715,-0.001199,0.003704,0.008874,0.012345,-0.000218,...,-0.013460,-0.001426,0.013519,-0.002783,0.006976,0.002856,0.008268,0.001716,-0.143964,0.500000
std,30222.571029,0.997888,0.021248,0.021151,0.022002,0.010814,0.049456,0.051304,0.276084,0.029839,...,0.095426,0.060287,0.071929,0.096647,0.026678,0.027228,0.067169,0.039354,1.061814,0.500006
min,837769.000000,-4.014821,-0.185741,-0.275342,-0.180744,-0.171254,-0.043520,-0.294782,0.000000,-0.495582,...,-0.466546,-0.855127,0.000000,-0.440235,-0.011070,-0.044373,0.000000,-0.243202,-3.909309,0.000000
25%,864061.500000,-0.827231,-0.008037,-0.012405,-0.009536,-0.000000,0.000000,0.000000,0.000000,-0.013505,...,-0.059884,-0.030131,0.000000,-0.043260,0.000000,0.000000,0.000000,-0.011407,-0.985416,0.000000
50%,890210.000000,-0.034572,0.000184,-0.001121,-0.000254,0.000000,0.000000,0.000000,0.000000,0.000006,...,-0.004658,-0.001757,0.000000,-0.001633,0.000000,0.000000,0.000000,0.000344,-0.217688,0.500000
75%,916324.250000,0.708763,0.008212,0.007983,0.006831,-0.000000,0.000000,0.000000,0.000000,0.014154,...,0.042496,0.025996,0.000000,0.035659,0.000000,0.000000,0.000000,0.013779,0.662565,1.000000
max,942487.000000,4.274689,0.460489,0.122380,0.374255,0.037208,1.017304,0.617568,6.600661,0.120577,...,0.768674,0.617547,0.607162,1.140550,0.210729,0.428857,0.965180,0.676102,3.961918,1.000000

In [22]:
df[df['period'] == 'train10'].describe()

,data_id,c1,c2,c3,c4,c5,c6,c7,c8,c9,...,c80,c81,c82,c83,c84,c85,c86,c87,c88,target
count,4.000000e+04,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,...,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000
mean,9.948504e+05,-0.000716,-0.001207,0.000415,0.000965,-0.000007,0.002235,0.004749,0.010214,-0.000701,...,-0.028307,-0.000641,0.012022,0.002492,0.006878,0.001995,0.003402,-0.000786,0.327036,0.500000
std,3.034760e+04,1.068889,0.018383,0.031643,0.051463,0.015979,0.037123,0.028017,0.228328,0.012962,...,0.151845,0.013224,0.063377,0.059558,0.026724,0.019729,0.028542,0.044905,1.021603,0.500006
min,9.424910e+05,-3.169335,-0.137199,-0.191532,-0.395972,-0.221279,-0.344917,-0.028885,0.000000,-0.139434,...,-0.814243,-0.132671,0.000000,-0.841120,-0.007013,-0.023800,-0.043776,-0.352860,-3.436239,0.000000
25%,9.684645e+05,-0.831260,-0.009157,-0.014695,-0.016585,0.000000,0.000000,0.000000,0.000000,-0.004361,...,-0.101740,-0.004305,0.000000,-0.018664,0.000000,0.000000,0.000000,-0.018909,-0.371179,0.000000
50%,9.947425e+05,0.013657,-0.000639,-0.000332,0.000671,0.000000,0.000000,0.000000,0.000000,-0.000280,...,-0.009901,-0.000035,0.000000,0.001664,0.000000,0.000000,0.000000,-0.000752,0.430904,0.500000
75%,1.021250e+06,0.828259,0.006197,0.012065,0.019626,0.000000,0.000000,0.000000,0.000000,0.002759,...,0.054633,0.003580,0.000000,0.025358,0.000000,0.000000,0.000000,0.014438,1.096382,1.000000
max,1.047206e+06,3.098332,0.290618,0.540909,1.010023,0.307539,0.503913,0.305147,5.415410,0.322109,...,0.845139,0.115765,0.534612,0.705282,0.236872,0.331741,0.431542,0.592784,3.709434,1.000000

In [23]:
df[df['period'] == 'train11'].describe()

,data_id,c1,c2,c3,c4,c5,c6,c7,c8,c9,...,c80,c81,c82,c83,c84,c85,c86,c87,c88,target
count,4.000000e+04,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,...,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000
mean,1.099683e+06,-0.084807,0.000317,-0.000903,0.000165,-0.001719,0.003376,0.007637,0.010073,-0.001530,...,-0.007979,-0.002478,0.009854,-0.001763,0.008942,0.003475,0.007439,0.000245,0.034989,0.500000
std,3.023179e+04,1.100561,0.015903,0.021346,0.022484,0.013737,0.045129,0.041511,0.225259,0.019326,...,0.065438,0.019393,0.051503,0.036761,0.033815,0.032191,0.063033,0.042416,1.030648,0.500006
min,1.047211e+06,-3.316366,-0.226652,-0.183998,-0.123323,-0.185447,-0.097980,0.000000,0.000000,-0.302433,...,-0.338916,-0.400332,0.000000,-0.696212,0.000000,-0.042849,-0.000041,-0.652250,-4.159360,0.000000
25%,1.073610e+06,-0.949448,-0.004927,-0.011408,-0.008557,-0.000000,0.000000,0.000000,0.000000,-0.008419,...,-0.034077,-0.009748,0.000000,-0.013518,0.000000,0.000000,0.000000,-0.014809,-0.708343,0.000000
50%,1.099739e+06,-0.098135,0.000103,-0.000438,-0.000049,0.000000,0.000000,0.000000,0.000000,-0.000962,...,-0.002107,-0.001044,0.000000,-0.000690,0.000000,0.000000,0.000000,0.000133,0.069781,0.500000
75%,1.125916e+06,0.750933,0.005649,0.009256,0.007927,-0.000000,0.000000,0.000000,0.000000,0.005482,...,0.025260,0.005494,0.000000,0.010041,0.000000,0.000000,0.000000,0.014875,0.812201,1.000000
max,1.151931e+06,3.651438,0.266217,0.324866,0.373586,-0.000000,0.893497,0.475261,5.533033,0.110702,...,0.804396,0.134328,0.427168,0.198776,0.245769,0.527906,0.954092,0.597612,3.143515,1.000000

In [24]:
df[df['period'] == 'train12'].describe()

,data_id,c1,c2,c3,c4,c5,c6,c7,c8,c9,...,c80,c81,c82,c83,c84,c85,c86,c87,c88,target
count,4.000000e+04,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,...,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000
mean,1.204387e+06,-0.145895,0.000337,0.000575,-0.003749,0.002363,0.003028,0.005669,0.004601,-0.002090,...,-0.019969,0.001265,0.008074,0.000072,0.005935,0.003180,0.004733,-0.000453,0.050921,0.500000
std,3.030270e+04,0.968246,0.027002,0.015100,0.096926,0.024105,0.047509,0.031273,0.103169,0.040534,...,0.141754,0.039619,0.042902,0.042300,0.023551,0.027688,0.039170,0.033624,0.970300,0.500006
min,1.151932e+06,-3.291608,-0.188465,-0.072247,-0.996743,-0.037275,-0.410262,-0.008301,0.000000,-0.455597,...,-0.993400,-0.517817,0.000000,-0.309409,-0.003677,0.000000,-0.086284,-0.266512,-3.264201,0.000000
25%,1.178135e+06,-0.893221,-0.010531,-0.005086,-0.051788,0.000000,0.000000,0.000000,0.000000,-0.023881,...,-0.091369,-0.014669,0.000000,-0.014074,0.000000,0.000000,0.000000,-0.015924,-0.662150,0.000000
50%,1.204440e+06,-0.204956,0.000872,-0.000048,-0.003711,0.000000,0.000000,0.000000,0.000000,-0.002401,...,-0.002003,0.000883,0.000000,-0.000109,0.000000,0.000000,0.000000,-0.000050,0.057974,0.500000
75%,1.230662e+06,0.573632,0.012540,0.004986,0.040738,0.000000,0.000000,0.000000,0.000000,0.020105,...,0.064264,0.018982,0.000000,0.014380,0.000000,0.000000,0.000000,0.014417,0.786611,1.000000
max,1.256652e+06,3.090520,0.379515,0.179448,0.855003,0.418434,0.802503,0.311808,2.645148,0.227661,...,0.497747,0.290437,0.374825,0.367152,0.180924,0.333402,0.573057,0.316999,3.599674,1.000000

In [25]:
df[df['period'] == 'train13'].describe()

,data_id,c1,c2,c3,c4,c5,c6,c7,c8,c9,...,c80,c81,c82,c83,c84,c85,c86,c87,c88,target
count,4.000000e+04,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,...,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000
mean,1.309107e+06,0.128504,-0.000034,-0.000389,-0.003203,0.000106,0.006537,0.008433,0.006298,0.000593,...,-0.017938,0.002342,0.008622,0.002026,0.006203,0.003729,0.007270,-0.000645,-0.360876,0.500000
std,3.012678e+04,1.042368,0.026120,0.022123,0.043841,0.008989,0.073799,0.045830,0.141173,0.024944,...,0.157305,0.021096,0.044905,0.207856,0.023998,0.034570,0.057398,0.018163,1.009084,0.500006
min,1.256658e+06,-3.721479,-0.200393,-0.164800,-0.354391,-0.120460,0.000000,0.000000,0.000000,-0.244684,...,-0.894578,-0.096259,0.000000,-2.123614,-0.004564,-0.085568,0.000000,-0.121019,-3.366547,0.000000
25%,1.282976e+06,-0.676339,-0.011488,-0.010633,-0.021518,0.000000,0.000000,0.000000,0.000000,-0.010547,...,-0.088508,-0.007624,0.000000,-0.091839,0.000000,0.000000,0.000000,-0.008078,-1.144575,0.000000
50%,1.309075e+06,0.160942,-0.000400,-0.000289,-0.000655,0.000000,0.000000,0.000000,0.000000,0.000438,...,0.011324,0.000012,0.000000,0.001715,0.000000,0.000000,0.000000,-0.000190,-0.459514,0.500000
75%,1.335147e+06,0.941842,0.010258,0.010101,0.016054,0.000000,0.000000,0.000000,0.000000,0.012782,...,0.085327,0.009169,0.000000,0.102777,0.000000,0.000000,0.000000,0.006605,0.383336,1.000000
max,1.361372e+06,3.798220,0.447287,0.238217,0.269391,0.172866,1.355478,0.519089,3.726267,0.252077,...,0.389266,0.167959,0.406174,0.945214,0.184831,0.468182,0.780890,0.127398,2.893680,1.000000

In [26]:
df[df['period'] == 'train14'].describe()

,data_id,c1,c2,c3,c4,c5,c6,c7,c8,c9,...,c80,c81,c82,c83,c84,c85,c86,c87,c88,target
count,4.000000e+04,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,...,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000
mean,1.413406e+06,0.326321,0.002907,-0.001008,-0.001121,0.000203,0.005706,0.007372,0.005736,0.000656,...,-0.028396,0.000689,0.007779,-0.007793,0.006269,0.002883,0.005812,0.003050,-0.216721,0.500000
std,3.023843e+04,1.003411,0.042152,0.014159,0.080737,0.009462,0.066467,0.041862,0.128150,0.018858,...,0.165549,0.016482,0.040461,0.104086,0.024806,0.027298,0.046123,0.037660,1.008369,0.500006
min,1.361374e+06,-3.584228,-0.291407,-0.101654,-1.737655,-0.130859,-0.056265,0.000000,0.000000,-0.309529,...,-0.883789,-0.111438,0.000000,-0.951977,-0.022967,-0.036611,0.000000,-0.600338,-3.814307,0.000000
25%,1.387222e+06,-0.389298,-0.016724,-0.006223,-0.032634,-0.000000,0.000000,0.000000,0.000000,-0.007010,...,-0.097345,-0.005397,0.000000,-0.063026,0.000000,0.000000,0.000000,-0.010015,-0.966899,0.000000
50%,1.413220e+06,0.411883,0.002227,-0.000275,0.000008,0.000000,0.000000,0.000000,0.000000,-0.000097,...,0.000422,0.000130,0.000000,-0.006989,0.000000,0.000000,0.000000,0.001145,-0.295683,0.500000
75%,1.439640e+06,1.061193,0.023826,0.003967,0.030978,0.000000,0.000000,0.000000,0.000000,0.006929,...,0.076170,0.007058,0.000000,0.050777,0.000000,0.000000,0.000000,0.017242,0.497087,1.000000
max,1.466094e+06,3.277988,0.207581,0.155703,0.377586,0.144709,1.159603,0.504450,2.927918,0.129213,...,0.474486,0.118643,0.353628,0.497947,0.201279,0.415038,0.621118,0.215584,3.271212,1.000000